# Generated by Django 3.2.6 on 2022-08-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=100, verbose_name='Телеграм токен')),
                ('tag', models.CharField(default='', max_length=100, verbose_name='Телеграм тэг')),
            ],
        ),
    ]
