# Generated by Django 3.2.6 on 2022-08-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220822_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='active_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ban',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bot_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kaspi_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kaspi_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kaspi_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parsing_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timer',
        ),
    ]
