# Generated by Django 3.2.6 on 2022-08-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='user',
            name='active_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата активности'),
        ),
    ]
