# Generated by Django 3.2.6 on 2022-08-22 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220822_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата активности'),
        ),
    ]
