# Generated by Django 3.2.6 on 2022-09-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_active_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pricelist',
            field=models.FileField(default='', upload_to='pricelists', verbose_name='Прайслит'),
        ),
    ]
