# Generated by Django 3.2.6 on 2022-09-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_pricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pricelist_exclude',
            field=models.TextField(default='', verbose_name='Не включать'),
        ),
    ]
