# Generated by Django 3.2.6 on 2022-09-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_pricelist_exclude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pricelist_exclude',
        ),
        migrations.AddField(
            model_name='user',
            name='kaspi_login',
            field=models.CharField(default='', max_length=100, verbose_name='Логин Kaspi'),
        ),
        migrations.AddField(
            model_name='user',
            name='kaspi_password',
            field=models.CharField(default='', max_length=100, verbose_name='Пароль Kaspi'),
        ),
    ]
