# Generated by Django 3.2.6 on 2022-09-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220910_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pricelist_xml',
            field=models.FileField(default='', upload_to='pricelists_xml', verbose_name='Прайслит XML'),
        ),
    ]
