# Generated by Django 4.1.1 on 2022-09-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_pricelist_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='free',
            field=models.BooleanField(default=False, verbose_name='Бесплатная'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена подписки'),
        ),
    ]
