# Generated by Django 4.1.1 on 2022-09-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_subscription_free_alter_subscription_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='free',
        ),
        migrations.AddField(
            model_name='user',
            name='kaspi_company',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Компания Kaspi'),
        ),
        migrations.AddField(
            model_name='user',
            name='kaspi_merchant_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Merchant ID Kaspi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kaspi_login',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Логин Kaspi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kaspi_password',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Пароль Kaspi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pricelist',
            field=models.FileField(blank=True, default='', upload_to='pricelists', verbose_name='Прайслит'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pricelist_xml',
            field=models.FileField(blank=True, default='', upload_to='pricelists_xml', verbose_name='Прайслит XML'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Telegram Id'),
        ),
    ]
