# Generated by Django 4.1.1 on 2022-09-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_subscription_free_user_kaspi_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pricelist_xlsx',
            field=models.FileField(blank=True, default='', upload_to='pricelists_xlsx', verbose_name='Прайслит XLSX'),
        ),
    ]
