# Generated by Django 4.1.1 on 2022-10-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_pricelist_xlsx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skip_merchant_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Пропуск ID компаний'),
        ),
    ]
